version: 2

sources:
  - name: PostgreSQL
    description: This is a replica of the data source postgreSQL
    database: DEV_DATAPLATFORM
    schema: RAW
    tables:
      - name: product
        description: >
          product details : master table.
        columns:
          - name: product_id
            description: Primary key of the product table
            tests:
              - unique
              - not_null
          - name: unit_price
            description: unit price of product

      - name: sales_trans
        description: "Sales transaction details."
        columns:
          - name: product_id
            description: product id's
            tests:
              - not_null
              
